### ISSUE TITLE
Train stage

### ISSUE THREAD

**Issue by lzzlxxlsz** [Shakarim94/CDnCNN-B-tensorflow#1]
in the train stage,I delete some pictures from ./data/CBSD432/ and it has 43 picures,I run the code main_blind.py,but in the sample folder ,it turns the pictures which are the pictures under the test folder

**Comment by Shakarim94** [comment]
You can output any image in the sample folder during training. Just change the line 36 in the main_blind.py file.
```
35. def denoiser_train(denoiser, lr):

36.     eval_files = natsort.natsorted(glob('./data/test/{}/*.png'.format(args.eval_set))) #change path here

37.     denoiser.train(args.data, eval_files, batch_size=args.batch_size, epoch=args.epoch, lr=lr)
```

**Comment by lzzlxxlsz** [comment]
but it is more likely a test stage,
