### ISSUE TITLE
how to use my own test dataset

### ISSUE THREAD

**Issue by fourteen14fourteen** [Shakarim94/CDnCNN-B-tensorflow#2]
how to use my own test data ,thanks

**Comment by Shakarim94** [comment]
Put your test data in ./data/test/my_test_data/ folder. Then you can perform tests with: 
```
python2 main_blind.py --phase=test --test_set=my_test_data
```

**Comment by fourteen14fourteen** [comment]
Does my test data also need to be noiseless, and then the program artificially adds noise to complete the test？

| |
fourteen_h
|
|
邮箱：fourteen_h@126.com
|

Signature is customized by Netease Mail Master

On 05/13/2019 13:24, Shakarim94 wrote:

Closed #2.

**Comment by Shakarim94** [comment]
It should be noiseless, then noise is added automatically. You can control the noise level as follows:
```
--sigma=50.0
```
sigma should be between 0 and 55.

**Comment by fourteen14fourteen** [comment]
Ok, what I want is to input the noisy picture of nature and view the effect, thank you! I'll study it myself




| |
fourteen_h
|
|
邮箱：fourteen_h@126.com
|

Signature is customized by Netease Mail Master

On 05/13/2019 21:08, Shakarim94 wrote:

It should be noiseless, then noise is added automatically. You can control the noise level as follows:

--sigma=50.0


sigma should be between 0 and 55.
