### ISSUE TITLE
Generating sigma values ...

### ISSUE THREAD

**Issue by eastchun** [Shakarim94/CDnCNN-B-tensorflow#3]
In line 151 in main_blind.py :

 # generating sigma values in range [0, 55]
 sigma_vector = np.random.uniform(0,55.0, data.shape[0]).astype('float32')`

why in range[0, 55]??  
Hasn't it to be range[0, args.sigma] ?

**Comment by Shakarim94** [comment]
That line is used to generate sigma values for training. Once the network is trained it can denoise images corrupted with any noise level in range [0,55].
 
args.sigma is only used to check the performance of the test or validation sets. It should be between 0 and 55.

**Comment by eastchun** [comment]
Thanks. 
While I was tracing your codes line by line, I forgot that this is for blind denoising.
